default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lusama_development
  username: postgres
  password: 'Def!n!te7'

test:
  <<: *default
  database: lusama_test
  username: postgres
  password: 'Def!n!te7'

production:
  <<: *default
  database: lusama_production
  username: postgres
  password: <%= ENV['LUSAMA_DATABASE_PASSWORD'] %>
